checks:
  ruby:
    code_rating: true
    duplicate_code: true

build:
  tests:
    override:
      -
        command: 'bundle exec rake test:scrutinizer'
        environment:
          'SCRUTINIZER_CC_FILE': 'my-coverage'
        coverage:
          file: 'my-coverage'
          format: 'rb-cc'

  project_setup:
    before:
      - mysql -e 'create database quizzy_test'
      - bundle exec rake db:migrate
