# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 407aeb2df8c6579de52337fc20ca69fec1793e0e4dfacf2a5d4e3973a40c9c0e2a1c22782d0774ecb5a37fdbc84c1668854845db31042a39212910879251d59a
  db_string: "mysql2://root@localhost/quizzy_development"

test:
  secret_key_base: 7b5f042e7870f3a3a1ce1cf48b9441e7a3d5327c231ea0d0fc6abc5e212e07a3dac66f2114c379d53ddb37f63b500c9fd67678c1765597b705e08ee469fc29c2
  db_string: "mysql2://root@localhost/quizzy_test"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_string: <%= ENV["QUIZZY_DATABASE_URL"] %>
